Update Dockerfile
Fixes missing python versions and failing installs with gems or due to openssl updates.

diff --git a/fbs/_defaults/src/build/docker/fedora/Dockerfile b/fbs/_defaults/src/build/docker/fedora/Dockerfile
--- a/fbs/_defaults/src/build/docker/fedora/Dockerfile
+++ b/fbs/_defaults/src/build/docker/fedora/Dockerfile
@@ -3,23 +3,59 @@ FROM fmanbuildsystem/fedora:25
 
 ARG requirements
 
-# Python 3.6:
-RUN dnf install -y python36
-
-# Absolute minimum requirements for building a PyQt5 app with PyInstaller:
-RUN dnf install -y libstdc++ freetype binutils
-
-# fpm:
-RUN dnf install -y ruby-devel gcc make rpm-build libffi-devel && \
-    gem install --no-ri --no-rdoc fpm
-
 WORKDIR /root/${app_name}
 
-# Set up virtual environment:
 ADD *.txt /tmp/requirements/
-RUN python3.6 -m venv venv && \
-    venv/bin/python -m pip install --upgrade pip && \
-    venv/bin/python -m pip install -r "/tmp/requirements/${requirements}"
+
+# Absolute minimum requirements for building a PyQt5 app with PyInstaller:
+RUN dnf -y update && \
+        dnf install -y libstdc++ freetype binutils git findutils && \
+        dnf clean all
+
+# Install base system libraries additionally specified by user.
+ENV USER_OS_DEPENDS /tmp/requirements/base_os_dependencies.txt
+RUN if [ -f "${USER_OS_DEPENDS}" ] && [ -s "${USER_OS_DEPENDS}" ] ; then dnf upgrade -y && \
+    dnf install -y $(cat /tmp/requirements/base_os_dependencies.txt) && \
+    dnf clean all; fi ||True
+
+
+# Pyenv minimum requirements : https://github.com/pyenv/pyenv/wiki#suggested-build-environment
+RUN dnf install -y make gcc zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel tk-devel \
+    libffi-devel xz
+
+# Set-up necessary Env vars for PyEnv
+ENV PYENV_ROOT /root/.pyenv
+ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
+
+# Reference: https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared
+ENV PYTHON_CONFIGURE_OPTS="--enable-shared"
+
+# Set default python version to file if provided and trim any whitepace.
+ENV DEFAULT_PYTHON_VERSION 3.6.12
+ENV PYTHON_VERSION_FILE /tmp/requirements/.python-version.txt
+RUN if [ -f "${PYTHON_VERSION_FILE}" ] && [ -s "${PYTHON_VERSION_FILE}" ] ; then \
+    echo "Existing PYTHON VERSION File found: ${PYTHON_VERSION_FILE}"; else \
+    echo "${DEFAULT_PYTHON_VERSION}" > "${PYTHON_VERSION_FILE}" ; fi
+
+# Install pyenv
+RUN set -ex \
+    && PYTHON_VERSION=$(cat /tmp/requirements/.python-version.txt | sed -e 's/^[[:space:]]*//') && cd "${HOME}" \
+    && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash \
+    && pyenv update \
+    && pyenv install "${PYTHON_VERSION}" \
+    && pyenv global "${PYTHON_VERSION}" \
+    && pyenv rehash
+
+
+# https://python-docs.readthedocs.io/en/latest/writing/gotchas.html
+ENV PYTHONDONTWRITEBYTECODE true
+
+# fpm: Set fallbacks for --no-document when later ruby is used which fails due to --no-ri --no-rdoc no longer existing
+RUN dnf install -y ruby-devel gcc make rpm-build libffi-devel && \
+    gem install --no-ri --no-rdoc fpm||gem install --no-document fpm
+
+# Upgrade pip and install Python pip packages needed:
+RUN pip install --upgrade pip && pip install -r "/tmp/requirements/${requirements}"
 RUN rm -rf /tmp/requirements/
 
 # Welcome message, displayed by ~/.bashrc:
